---
name: Upload Packages to new release

'on':
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git tag to push the image'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          # Otherwise there's a risk to not get latest tag
          # We hope, that the current commit at
          # least 100 commits close to the latest release
          fetch-depth: 100
          fetch-tags: ${{ inputs.ref != '' }}
          ref: ${{ inputs.ref }}
      - name: Set up Go 1
        uses: actions/setup-go@v5
        with:
          go-version: ^1
      - name: Build packages
        id: build
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.40.0
          make -e CGO_ENABLED=0 packages
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="${{ inputs.ref && inputs.ref || github.event.release.tag_name }}"
          gh release upload --repo ${{ github.repository }} "$TAG" \
              out/*.deb out/*.rpm out/*sum
      - name: Upload packages to packagecloud.com
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          go install github.com/mlafeldt/pkgcloud/cmd/pkgcloud-push@e79e9efc
          make packagecloud-stable
